### ISSUE TITLE
[BUG]: logo rendering not responsive

### ISSUE THREAD

**Issue by getlarge** [material-identity/schema-definitions#18]
**Describe the bug**

In the HMTL rendering of the certificate, the logo does not seem to scale when reducing HTML document size and it steps on the Parties description

**Screenshots**

<img width="811" alt="Screenshot 2023-01-25 at 08 57 32" src="https://user-images.githubusercontent.com/15331923/215413658-4f2cd9d9-20f0-48b8-8658-eaabd4e0b42a.png">

**Additional context**
Seen in S1SEVEN's verification app.

**Comment by getlarge** [comment]
The logo definition and rendering is now done through the `CommercialTransaction-> CommercialTransactionBase ->A04`

**Comment by eamon0989** [comment]
The issue was caused by the image `max-width` being bigger than the parent container (it was set to 20vw). Setting the `max-width` to 100% of the parent container solves the problem. The fix should be done in the the `EN10168-schemas ` repository as that is where the handlebars template resides.
